FROM quay.io/openshift/origin-base:4.10

RUN cd /usr/bin && \
    ln -s control-plane-operator ignition-server && \
    ln -s control-plane-operator konnectivity-socks5-proxy && \
    ln -s control-plane-operator availability-prober && \
    ln -s control-plane-operator token-minter

LABEL io.openshift.hypershift.control-plane-operator-subcommands=true
LABEL io.openshift.hypershift.ignition-server-healthz-handler=true
COPY bin/* /usr/bin/
ENTRYPOINT /usr/bin/hypershift
